-- ============================================================================
-- RNB Onboarding — core schema
-- ============================================================================
-- The brain replacing the Make scenario "Add new sales reps in Teams" + the
-- Google Sheet tracker + Jotform checklist. Side effects NEVER fire inline:
-- API routes write onboarding.outbox rows and the mac-mini worker executes
-- them behind send gates (queue-row boundary, inherited from the leasing stack).
-- ============================================================================

-- ── Enums ───────────────────────────────────────────────────────────────────
create type onboarding.rep_status as enum (
  'invited',          -- manager kicked off; welcome/info-form SMS queued
  'info_submitted',   -- rep info form received
  'contract_sent',    -- gusto contract sent (manual step recorded)
  'contract_signed',  -- clear to provision
  'provisioning',     -- accounts being created (M365 / Teams / HCP)
  'active',           -- fully onboarded
  'inactive'          -- abandoned / terminated
);

create type onboarding.item_status as enum ('pending', 'done', 'skipped', 'blocked');

create type onboarding.outbox_state as enum ('pending', 'in_flight', 'done', 'failed', 'skipped');

-- ── Config tables (Settings UI) ─────────────────────────────────────────────
create table onboarding.territories (
  id                  bigint generated by default as identity primary key,
  name                text not null unique,
  active              boolean not null default true,
  -- Teams chat ids the new rep gets added to (post-sales channels etc.)
  post_sales_chat_ids jsonb not null default '[]'::jsonb,
  -- HCP company/org for this territory. The API key itself stays in env:
  -- hcp_api_key_env names the env var the worker reads (keys never live in DB).
  hcp_company_note    text,
  hcp_api_key_env     text,
  gusto_note          text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create trigger trg_territories_updated_at before update on onboarding.territories
  for each row execute function shared.set_updated_at();

-- Internal stakeholders referenced by automations (replaces hardcoded Azure ids
-- in the Make scenario). `roles` drives membership:
--   phone_room_roster        — added to every new rep's Phone Room group chat
--   welcome_email_bcc        — bcc'd on the welcome email
--   business_card_contact    — receives the business-card request email
--   admin_notify             — notified when a rep submits their info form
-- `territories` non-empty limits a role to those territories (e.g. a regional
-- manager only joins Phone Rooms in their region); empty = all territories.
create table onboarding.people (
  id            bigint generated by default as identity primary key,
  full_name     text not null,
  email         text,
  azure_user_id text,
  phone         text,
  roles         text[] not null default '{}',
  territories   text[] not null default '{}',
  active        boolean not null default true,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create trigger trg_people_updated_at before update on onboarding.people
  for each row execute function shared.set_updated_at();

-- Message bodies the automations send — seeded from the captured Make scenario,
-- editable in Settings. Vars use {{snake_case}} tokens rendered by the worker.
create table onboarding.message_templates (
  key         text primary key,
  channel     text not null check (channel in ('sms', 'teams', 'email')),
  subject     text,                -- email only
  body        text not null,
  description text,
  updated_at  timestamptz not null default now()
);
create trigger trg_message_templates_updated_at before update on onboarding.message_templates
  for each row execute function shared.set_updated_at();

-- Simple key/value app settings (welcome-email sender mailbox, company-wide
-- chat id, admin notification email, kill switch mirror, …).
create table onboarding.app_settings (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz not null default now()
);
create trigger trg_app_settings_updated_at before update on onboarding.app_settings
  for each row execute function shared.set_updated_at();

-- The checklist template — instantiated per rep on info submission.
-- automation_key names the bundle of outbox actions completion enqueues
-- (resolved in lib/onboarding/automations.ts); null = purely manual step.
create table onboarding.checklist_templates (
  key            text primary key,
  label          text not null,
  sort_order     int not null,
  automation_key text,
  auto           boolean not null default false,  -- completed by the system, not a human
  active         boolean not null default true,
  description    text
);

-- ── Reps ────────────────────────────────────────────────────────────────────
create table onboarding.reps (
  id              bigint generated by default as identity primary key,
  first_name      text not null,
  last_name       text not null,
  personal_email  text,
  phone_e164      text,                       -- +1XXXXXXXXXX
  phone_os        text,                       -- iOS | Android (drives app-download SMS)
  home_address    text,
  zip_code        text,
  dob             date,
  how_heard       text,
  manager_name    text,
  territory_id    bigint references onboarding.territories (id),
  expected_start  date,
  status          onboarding.rep_status not null default 'invited',
  -- provisioning results
  rnb_email           text,
  m365_user_id        text,
  m365_temp_password  text,                   -- surfaced once in drawer; cleared after first login
  teams_chat_id       text,                   -- 1:1 chat with Robert
  phone_room_chat_id  text,
  hcp_employee_id     text,
  hcp_username        text,
  gusto_status        text,
  greensky_status     text,
  training_passed_at  timestamptz,
  -- intake / form linkage
  jotform_info_submission_id text unique,     -- rep-info form submission (prefilled + edited)
  info                jsonb not null default '{}'::jsonb,  -- extra rep-form fields (shirt size, …)
  is_test             boolean not null default false,
  notes               text,
  created_by          uuid references shared.profiles (id),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create trigger trg_reps_updated_at before update on onboarding.reps
  for each row execute function shared.set_updated_at();
create index reps_status_idx on onboarding.reps (status);
create index reps_territory_idx on onboarding.reps (territory_id);

-- Per-rep instantiated checklist.
create table onboarding.checklist_items (
  id             bigint generated by default as identity primary key,
  rep_id         bigint not null references onboarding.reps (id) on delete cascade,
  template_key   text not null references onboarding.checklist_templates (key),
  label          text not null,
  sort_order     int not null,
  automation_key text,
  status         onboarding.item_status not null default 'pending',
  completed_by   uuid references shared.profiles (id),
  completed_at   timestamptz,
  notes          text,
  unique (rep_id, template_key)
);
create index checklist_items_rep_idx on onboarding.checklist_items (rep_id, sort_order);

-- ── Outbox — the ONLY path to external side effects ─────────────────────────
-- API routes insert rows; the worker (mac mini, launchd, 60s) executes them via
-- lib/connectors with the gate stack (dry-run default, kill switch, allowlist).
create table onboarding.outbox (
  id          bigint generated by default as identity primary key,
  action_type text not null,                  -- dispatch key, e.g. 'sms.send', 'm365.create_user'
  rep_id      bigint references onboarding.reps (id) on delete set null,
  payload     jsonb not null default '{}'::jsonb,
  state       onboarding.outbox_state not null default 'pending',
  attempts    int not null default 0,
  last_error  text,
  dedupe_key  text unique,                    -- idempotency across re-enqueues; null = no dedupe
  run_after   timestamptz not null default now(),
  created_at  timestamptz not null default now(),
  executed_at timestamptz,
  dry_run_log jsonb                           -- what WOULD have been sent when gated
);
create index outbox_pending_idx on onboarding.outbox (state, run_after) where state = 'pending';
create index outbox_rep_idx on onboarding.outbox (rep_id, created_at desc);

-- ── Raw form submissions (audit + replay) ───────────────────────────────────
create table onboarding.form_submissions (
  id            bigint generated by default as identity primary key,
  source        text not null,                -- 'jotform_info' | 'native_intake' | …
  form_id       text,
  submission_id text unique,
  rep_id        bigint references onboarding.reps (id) on delete set null,
  payload       jsonb not null default '{}'::jsonb,
  received_at   timestamptz not null default now()
);

-- ── Delegated OAuth token store (Graph chat sends as a real user) ───────────
-- refresh_token_enc is AES-256-GCM encrypted with TOKEN_ENCRYPTION_KEY (env);
-- only the worker and the OAuth callback route touch this table (service role).
create table onboarding.oauth_tokens (
  provider          text primary key,         -- 'microsoft-delegated'
  account_label     text,                     -- upn of the consented account
  refresh_token_enc text not null,
  scopes            text,
  updated_at        timestamptz not null default now()
);
create trigger trg_oauth_tokens_updated_at before update on onboarding.oauth_tokens
  for each row execute function shared.set_updated_at();

-- ── Rep hub links (token auth — reps have no Supabase login) ────────────────
create table onboarding.rep_links (
  id         bigint generated by default as identity primary key,
  rep_id     bigint not null references onboarding.reps (id) on delete cascade,
  token      text not null unique default encode(gen_random_bytes(24), 'hex'),
  active     boolean not null default true,
  created_at timestamptz not null default now(),
  last_seen  timestamptz
);
create index rep_links_rep_idx on onboarding.rep_links (rep_id);

-- ── Compatibility: employee_teams_chats ─────────────────────────────────────
-- The Make "Dialpad" scenario reads public.employee_teams_chats to route sales
-- reporting. If this app is deployed into the SAME project that table already
-- lives in, this create is a no-op; on a fresh project it recreates the shape
-- so the compat writer (outbox action compat.employee_teams_chats) always works.
create table if not exists public.employee_teams_chats (
  id                          bigint generated by default as identity primary key,
  assigned_employee_first_name text,
  assigned_employee_last_name  text,
  assigned_employee_email      text,
  location                     text,
  chat_id                      text,
  phone_room_chat_id           text,
  created_at                   timestamptz not null default now()
);

-- ── RLS + grants (webapp is fully authenticated; worker uses service role) ──
do $$
declare t text;
begin
  foreach t in array array[
    'territories','people','message_templates','app_settings','checklist_templates',
    'reps','checklist_items','outbox','form_submissions','rep_links'
  ] loop
    execute format('alter table onboarding.%I enable row level security', t);
    execute format(
      'create policy %I_all on onboarding.%I for all to authenticated using (true) with check (true)',
      t, t);
    execute format('grant select, insert, update, delete on onboarding.%I to authenticated', t);
    execute format('grant select, insert, update, delete on onboarding.%I to service_role', t);
  end loop;
end $$;

-- oauth_tokens: service_role only — never exposed to the browser session.
alter table onboarding.oauth_tokens enable row level security;
grant select, insert, update, delete on onboarding.oauth_tokens to service_role;

grant usage, select on all sequences in schema onboarding to authenticated, service_role;
