-- Login-free intake, one link per city.
--
-- The managers who file new reps were never given app credentials, so the
-- form they need most sits behind a login nobody has. This gives each city a
-- permanent tokenized URL (/intake/<token>) that opens the form directly.
--
-- The link is scoped to a city on purpose: territory is the field the
-- automations hang off — Phone Room roster, regional chats, the HCP company and
-- key, the M365 office, the manager copied on the welcome email. A rep filed
-- under the wrong city is wrong in five places before anyone notices, while a
-- misspelled name is a ten-second fix in the drawer. So the city comes from the
-- link and the form cannot change it.
--
-- The token IS the credential: anyone holding it can file a rep in that city
-- (and each filing texts the phone number typed into the form). Hence `active`,
-- one live link per city, and `intake_link_id` on the rep — so a leaked link
-- can be cut off and every rep it created can be traced back to it.

create table onboarding.intake_links (
  id           bigint generated by default as identity primary key,
  territory_id bigint not null references onboarding.territories (id) on delete cascade,
  token        text not null unique default encode(gen_random_bytes(24), 'hex'),
  active       boolean not null default true,
  note         text,
  uses         int not null default 0,
  last_used_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
-- Rotating a link = deactivate the old row, insert a new one. The partial index
-- keeps exactly one live link per city, so there is never an orphan URL still
-- working after a rotation.
create unique index intake_links_one_active_per_territory
  on onboarding.intake_links (territory_id) where active;
create trigger trg_intake_links_updated_at before update on onboarding.intake_links
  for each row execute function shared.set_updated_at();

alter table onboarding.intake_links enable row level security;
create policy intake_links_all on onboarding.intake_links
  for all to authenticated using (true) with check (true);
grant select, insert, update, delete on onboarding.intake_links to authenticated, service_role;

-- Provenance: which link filed this rep (null = filed from inside the webapp).
alter table onboarding.reps
  add column intake_link_id bigint references onboarding.intake_links (id) on delete set null;

insert into onboarding.intake_links (territory_id, note)
select id, 'Seeded 2026-08-26' from onboarding.territories where active;

-- Which managers the city's form offers. Only what the reps' own history
-- supports is claimed here — Guzman took Arizona today, Faronea's reps are the
-- Tampa ones, Talmage's are OC/IE. Everyone else stays unmapped and shows up
-- under "Other managers" until someone fills this in from Settings → People.
update onboarding.people
   set roles = array(select distinct unnest(roles || '{manager}'::text[]))
 where full_name in ('Chris Faronea', 'Jason Talmage')
   and territories <@ '{Tampa,OC/IE}'::text[]
   and active;

update onboarding.people p
   set email = pr.email
  from shared.profiles pr
 where p.email is null
   and 'manager' = any (p.roles)
   and lower(pr.full_name) = lower(p.full_name);
