-- ============================================================================
-- RNB Onboarding — shared baseline
-- ============================================================================
-- Pattern inherited from GCVPM OS (gcv-renewals 20260714120000_baseline_shared):
-- shared.profiles auto-provisioned from auth.users, plus the OS-wide audit
-- primitive shared.entity_activity.
--
-- IMPORTANT (SETUP.md): after applying, add `onboarding, training, shared` to
-- the project's Exposed Schemas (API settings) so PostgREST can serve them.
-- ============================================================================

create extension if not exists pgcrypto;

create schema if not exists shared;
create schema if not exists onboarding;
create schema if not exists training;
grant usage on schema shared to authenticated, service_role;
grant usage on schema onboarding to authenticated, service_role;
grant usage on schema training to authenticated, service_role;

-- ── Enums ───────────────────────────────────────────────────────────────────
create type shared.profile_role as enum ('admin', 'manager', 'staff');
create type shared.entity_type as enum ('rep');
create type shared.actor_kind as enum ('user', 'system', 'unknown');

-- ── Helper functions ────────────────────────────────────────────────────────
create or replace function shared.set_updated_at()
 returns trigger
 language plpgsql
 set search_path to ''
as $function$
begin new.updated_at = now(); return new; end $function$;

-- Auto-provision a shared.profiles row when a new auth.users row is inserted.
create or replace function shared.handle_new_user()
 returns trigger
 language plpgsql
 security definer
 set search_path to ''
as $function$
begin
  insert into shared.profiles (id, email, full_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', new.email))
  on conflict (id) do nothing;
  return new;
end $function$;

grant execute on function shared.set_updated_at() to anon, authenticated, service_role;
grant execute on function shared.handle_new_user() to anon, authenticated, service_role;

-- ── Tables ──────────────────────────────────────────────────────────────────
create table shared.profiles (
  id         uuid not null,
  email      text,
  full_name  text,
  role       shared.profile_role not null default 'staff',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign key (id) references auth.users (id) on delete cascade
);

create trigger trg_profiles_updated_at
  before update on shared.profiles
  for each row execute function shared.set_updated_at();

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function shared.handle_new_user();

-- The OS-wide audit primitive: who did what to which entity, when.
create table shared.entity_activity (
  id          bigint generated by default as identity,
  entity_type shared.entity_type not null,
  entity_id   text not null,                  -- polymorphic; NO fk (audit outlives entity)
  actor_id    uuid,
  actor_type  shared.actor_kind not null default 'unknown',
  actor_label text,                            -- display: user email, or system job name
  action      text not null,                   -- module-specific verb
  summary     text,
  payload     jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  constraint entity_activity_pkey primary key (id),
  constraint entity_activity_actor_id_fkey foreign key (actor_id)
    references shared.profiles (id) on delete set null
);

create index entity_activity_entity_idx on shared.entity_activity
  using btree (entity_type, entity_id, occurred_at desc);

-- ── RLS + grants ────────────────────────────────────────────────────────────
alter table shared.profiles enable row level security;
create policy profiles_select_auth on shared.profiles
  for select to authenticated using (true);
create policy profiles_update_own on shared.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
grant select, update on shared.profiles to authenticated;
grant select, insert, update, delete on shared.profiles to service_role;

alter table shared.entity_activity enable row level security;
create policy entity_activity_select_auth on shared.entity_activity
  for select to authenticated using (true);
create policy entity_activity_insert_auth on shared.entity_activity
  for insert to authenticated with check (true);
grant select, insert on shared.entity_activity to authenticated;
grant select, insert, update, delete on shared.entity_activity to service_role;
