-- ============================================================================
-- RNB Onboarding — training schema
-- ============================================================================
-- Curriculum + readiness test. Admins author courses/lessons/quizzes in the
-- webapp; reps consume them from their tokenized hub (/my/<token>) via
-- service-role reads — the `anon` role gets NO grants here.
-- Passing the final quiz stamps reps.training_passed_at and completes the
-- 'training' checklist item (done in the API route, which also logs activity).
-- ============================================================================

create table training.courses (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  sort_order  int not null default 0,
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger trg_courses_updated_at before update on training.courses
  for each row execute function shared.set_updated_at();

create table training.lessons (
  id         bigint generated by default as identity primary key,
  course_id  bigint not null references training.courses (id) on delete cascade,
  title      text not null,
  content_md text,                             -- markdown body
  video_url  text,                             -- optional embed (SharePoint/YouTube/Loom)
  sort_order int not null default 0,
  active     boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_lessons_updated_at before update on training.lessons
  for each row execute function shared.set_updated_at();
create index lessons_course_idx on training.lessons (course_id, sort_order);

create table training.quizzes (
  id         bigint generated by default as identity primary key,
  course_id  bigint references training.courses (id) on delete cascade,
  title      text not null,
  pass_pct   int not null default 80 check (pass_pct between 1 and 100),
  is_final   boolean not null default false,  -- passing the final gates the checklist
  active     boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_quizzes_updated_at before update on training.quizzes
  for each row execute function shared.set_updated_at();

create table training.questions (
  id            bigint generated by default as identity primary key,
  quiz_id       bigint not null references training.quizzes (id) on delete cascade,
  prompt        text not null,
  options       jsonb not null,               -- ["option A", "option B", …]
  correct_index int not null,
  sort_order    int not null default 0,
  active        boolean not null default true
);
create index questions_quiz_idx on training.questions (quiz_id, sort_order);

create table training.attempts (
  id         bigint generated by default as identity primary key,
  quiz_id    bigint not null references training.quizzes (id) on delete cascade,
  rep_id     bigint not null references onboarding.reps (id) on delete cascade,
  answers    jsonb not null,                  -- {question_id: chosen_index}
  score_pct  numeric(5,2) not null,
  passed     boolean not null,
  created_at timestamptz not null default now()
);
create index attempts_rep_idx on training.attempts (rep_id, created_at desc);

-- ── RLS + grants ────────────────────────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array['courses','lessons','quizzes','questions','attempts'] loop
    execute format('alter table training.%I enable row level security', t);
    execute format(
      'create policy %I_all on training.%I for all to authenticated using (true) with check (true)',
      t, t);
    execute format('grant select, insert, update, delete on training.%I to authenticated', t);
    execute format('grant select, insert, update, delete on training.%I to service_role', t);
  end loop;
end $$;

grant usage, select on all sequences in schema training to authenticated, service_role;
