-- Listening for the Gusto contract signature.
--
-- Gusto never sends a mail that says "signed". The only signal is the one that
-- lands in the admin inbox — "<Name> from <Company> can now be paid", body
-- "has finished setting up their Gusto account". The worker watches that
-- mailbox, matches the rep, auto-checks the Gusto checklist item and texts ops.
--
-- Worth knowing about the ordering: the item is normally checked BEFORE the
-- signature arrives (Philip Carver — item checked and welcome sent 17:47, Gusto
-- mail 18:35), so the auto-check is usually a no-op and the text is what
-- carries the news. It still earns its place for the reps whose manager never
-- gets around to checking the box.

create table onboarding.gusto_signature_events (
  id                  bigint generated by default as identity primary key,
  -- The mail's own id: idempotency, so a message seen by two passes fires once.
  internet_message_id text not null unique,
  graph_message_id    text,
  subject             text not null,
  received_at         timestamptz not null,
  gusto_name          text,
  gusto_company       text,
  rep_id              bigint references onboarding.reps (id) on delete set null,
  matched             boolean not null default false,
  note                text,
  created_at          timestamptz not null default now()
);
create index gusto_signature_events_received_idx
  on onboarding.gusto_signature_events (received_at desc);

alter table onboarding.gusto_signature_events enable row level security;
create policy gusto_signature_events_all on onboarding.gusto_signature_events
  for all to authenticated using (true) with check (true);
grant select, insert, update, delete on onboarding.gusto_signature_events to authenticated, service_role;

insert into onboarding.app_settings (key, value) values
  ('gusto_signature_watch_enabled', 'true'),
  ('gusto_signature_sender',        '"gustonoreply@gusto.com"'),
  -- Which mailbox receives them; empty falls back to admin_upn.
  ('gusto_signature_mailbox',       '""'),
  -- Watermark. Starts at "now" on purpose: the four signatures already sitting
  -- in the inbox belong to reps whose Gusto item is long since checked, and
  -- replaying them would only fire four pointless texts.
  ('gusto_signature_cursor',        to_jsonb(now()))
on conflict (key) do nothing;

insert into onboarding.message_templates (key, channel, subject, body, description) values
  ('sms.gusto_signed_ops', 'sms', null,
   E'✍️ Gusto: {{first_name}} {{last_name}} ({{territory}}) finished setting up their Gusto account — contract signed.\n{{checklist_note}}',
   'Ops-only text when the Gusto "can now be paid" mail arrives. Goes to sms_copy_to.')
on conflict (key) do nothing;
